//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.05 at 03:39:41 PM CET 
//


package de.hpi.bpmn2_0.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;

import de.hpi.bpmn2_0.model.event.EventDefinition;


/**
 * <p>Java class for tNgsiEventDefinition complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tNgsiEventDefinition">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.omg.org/spec/BPMN/20100524/MODEL}tEventDefinition">
 *       &lt;sequence>
 *         &lt;element name="attributeList" type="{http://www.omg.org/spec/BPMN/20100524/MODEL}tAttributeList" minOccurs="0"/>
 *         &lt;element name="notifyCondition" type="{http://www.omg.org/spec/BPMN/20100524/MODEL}tNotifyCondition" minOccurs="0"/>
 *         &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}duration" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tNgsiEventDefinition", propOrder = {
    "attributeList",
    "notifyCondition",
    "duration"
})
@XmlRootElement(name = "ngsiEventDefinition")
public class NgsiEventDefinition
    extends EventDefinition
{

    protected AttributeList attributeList;
    protected NotifyCondition notifyCondition;
    protected Duration duration;

    /**
     * Gets the value of the attributeList property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeList }
     *     
     */
    public AttributeList getAttributeList() {
        return attributeList;
    }

    /**
     * Sets the value of the attributeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeList }
     *     
     */
    public void setAttributeList(AttributeList value) {
        this.attributeList = value;
    }

    /**
     * Gets the value of the notifyCondition property.
     * 
     * @return
     *     possible object is
     *     {@link NotifyCondition }
     *     
     */
    public NotifyCondition getNotifyCondition() {
        return notifyCondition;
    }

    /**
     * Sets the value of the notifyCondition property.
     * 
     * @param value
     *     allowed object is
     *     {@link NotifyCondition }
     *     
     */
    public void setNotifyCondition(NotifyCondition value) {
        this.notifyCondition = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setDuration(Duration value) {
        this.duration = value;
    }

}
