//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.22 at 07:59:21 PM CEST 
//


package de.hpi.bpmn2_0.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tNotifyConditionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tNotifyConditionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ONTIMEINTERVAL"/>
 *     &lt;enumeration value="ONVALUE"/>
 *     &lt;enumeration value="ONCHANGE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "tNotifyConditionType")
@XmlEnum
public enum NotifyConditionType {

    ONTIMEINTERVAL,
    ONVALUE,
    ONCHANGE,
    NONE;

    public String value() {
        return name();
    }

    public static NotifyConditionType fromValue(String v) {
        return valueOf(v);
    }

}
